// Command ociger-ck-identity is the boot-time provisioner for the ck-allinone
// NATS auth-callout account (bundle v0.7.30). It runs as an s6 oneshot BEFORE
// the nats and postgres longruns and closes the last identity hop by making the
// broker's callout issuer and pgCK's signing seed the SAME account, every boot:
//
//  1. Resolve the callout ACCOUNT nkey pair. OCIGER_NATS_ACCOUNT_SEED, if the
//     operator supplied one, gives a STABLE account; otherwise a fresh account
//     is minted per boot (ephemeral — clients simply reconnect).
//  2. Resolve the pgck_worker bypass password (OCIGER_NATS_WORKER_PASSWORD, else
//     a fresh random one).
//  3. Write /etc/nats/nats-server.conf with the auth_callout stanza — issuer is
//     the account PUBLIC key; pgck_worker is the sole auth_user that bypasses
//     the callout so pgCK's own connection can service $SYS.REQ.USER.AUTH.
//  4. Write /run/ck-identity/pgck.conf with pgck.nats_account_seed (the PRIVATE
//     half pgCK signs admittance with) + pgck.nats_url (worker creds). postgres
//     pulls it in via `include_if_exists` at every start, so the seed the
//     responder signs with always matches the issuer the broker verifies.
//
// The seed is NEVER baked into the image: absent an operator seed it is minted
// fresh each boot and lives only in tmpfs (/run) and process memory.
package main

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"log"
	"net/url"
	"os"
	"path/filepath"
	"strings"

	"github.com/nats-io/nkeys"
)

const (
	defaultNatsConf = "/etc/nats/nats-server.conf"
	defaultPgckConf = "/run/ck-identity/pgck.conf"
	workerUser      = "pgck_worker"
	natsCorePort    = 4222
	natsWssPort     = 9222
)

func main() {
	natsConf := getenv("OCIGER_NATS_CONF", defaultNatsConf)
	pgckConf := getenv("OCIGER_PGCK_CONF", defaultPgckConf)

	seed, pub, err := resolveAccount(os.Getenv("OCIGER_NATS_ACCOUNT_SEED"))
	if err != nil {
		log.Fatalf("ociger-ck-identity: account key: %v", err)
	}
	workerPass, err := resolveWorkerPassword(os.Getenv("OCIGER_NATS_WORKER_PASSWORD"))
	if err != nil {
		log.Fatalf("ociger-ck-identity: worker password: %v", err)
	}

	// nats-server.conf world-readable (nats reads it); pgck.conf carries the
	// seed so keep it tighter (0640 — the container is single-tenant, postgres
	// reads it as its own uid via the include).
	if err := writeFileMode(natsConf, natsServerConf(pub, workerPass), 0o644); err != nil {
		log.Fatalf("ociger-ck-identity: write %s: %v", natsConf, err)
	}
	if err := writeFileMode(pgckConf, pgckSecretsConf(seed, workerPass), 0o640); err != nil {
		log.Fatalf("ociger-ck-identity: write %s: %v", pgckConf, err)
	}

	source := "minted per-boot (ephemeral)"
	if strings.TrimSpace(os.Getenv("OCIGER_NATS_ACCOUNT_SEED")) != "" {
		source = "operator-supplied (OCIGER_NATS_ACCOUNT_SEED)"
	}
	log.Printf("ociger-ck-identity: auth-callout account %s [%s]; wrote %s + %s", pub, source, natsConf, pgckConf)
}

// resolveAccount returns the account seed (canonical string form, e.g. "SA...")
// and its public key. A non-empty seedEnv MUST parse as an ACCOUNT nkey seed
// (operator override → stable identity); otherwise a fresh account is minted.
func resolveAccount(seedEnv string) (seed string, pub string, err error) {
	var kp nkeys.KeyPair
	if s := strings.TrimSpace(seedEnv); s != "" {
		kp, err = nkeys.FromSeed([]byte(s))
		if err != nil {
			return "", "", fmt.Errorf("OCIGER_NATS_ACCOUNT_SEED is not a valid nkey seed: %w", err)
		}
	} else {
		kp, err = nkeys.CreateAccount()
		if err != nil {
			return "", "", err
		}
	}
	pub, err = kp.PublicKey()
	if err != nil {
		return "", "", err
	}
	// Account public keys are prefixed 'A'. Reject a user/operator/server seed —
	// the callout issuer must be an account, or the broker rejects every mint.
	if !strings.HasPrefix(pub, "A") {
		return "", "", fmt.Errorf("resolved key is not an ACCOUNT nkey (public key %q must start with 'A')", pub)
	}
	sb, err := kp.Seed()
	if err != nil {
		return "", "", err
	}
	return string(sb), pub, nil
}

// resolveWorkerPassword returns the operator-supplied password verbatim, or a
// fresh 24-byte random hex string.
func resolveWorkerPassword(envPass string) (string, error) {
	if p := strings.TrimSpace(envPass); p != "" {
		return p, nil
	}
	b := make([]byte, 24)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

// natsServerConf renders the server-config-mode auth_callout config. Every
// connection that is NOT an auth_user is routed to the in-extension responder,
// which admits a verified bearer as its id-scoped identity or (absent/invalid)
// as anonymous subscribe-only. This supersedes the interim forge-deny: an anon
// client cannot publish at all.
func natsServerConf(issuerPub, workerPass string) string {
	return fmt.Sprintf(`# GENERATED by ociger-ck-identity at boot — DO NOT EDIT.
# Regenerated every boot from the resolved auth-callout account (issuer below).
port: %d
websocket {
  port: %d
  no_tls: true
}
authorization {
  users: [
    { user: %s, password: %q }
  ]
  auth_callout {
    issuer: %q
    auth_users: [ %s ]
  }
}
`, natsCorePort, natsWssPort, workerUser, workerPass, issuerPub, workerUser)
}

// pgckSecretsConf renders the postgresql.conf fragment postgres pulls in via
// `include_if_exists`. nats_url carries the worker bypass creds (URL-encoded so
// an operator-supplied password with reserved characters stays well-formed).
func pgckSecretsConf(seed, workerPass string) string {
	u := url.URL{
		Scheme: "nats",
		User:   url.UserPassword(workerUser, workerPass),
		Host:   fmt.Sprintf("127.0.0.1:%d", natsCorePort),
	}
	return fmt.Sprintf(`# GENERATED by ociger-ck-identity at boot — DO NOT EDIT.
pgck.nats_account_seed = '%s'
pgck.nats_url = '%s'
`, seed, u.String())
}

func writeFileMode(path, contents string, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(contents), mode)
}

func getenv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
